### ISSUE TITLE
Sometimes upon entering a battle mid-turn, it spawns notes immediately for the current measure rather than waiting for the next measure.

### ISSUE THREAD

**Issue by armsnyder** [armsnyder/countermelody#111]

**Comment by armsnyder** [comment]
I think I figured this one out - if you enter battle on the first beat of a measure and slightly ahead of the beat, the bug happens. It's because the current measure technically hasn't started, so it retrieves battle notes for what it thinks is the next measure, but is functionally the current measure.

**Comment by cegrief** [comment]
I'm absurdly bad at making this happen when i want to for some reason, so i'm having a lot of trouble trying to debug :P

**Comment by armsnyder** [comment]
Reopening because during demo this happened twice with slightly different behavior - current measure AND next measure would both play if entering battle on beat 1, resulting in 2 measures of battle.

**Comment by armsnyder** [comment]
I discovered this happens only upon triggering a battle on the last measure of the song, a split second before the first beat. Woah.

**Comment by armsnyder** [comment]
Excuuuuuse me. I meant, if you trigger a battle on the first beat of the first measure.
