### ISSUE TITLE
Occasionally, the battle exits mid-measure before all the notes have flown by

### ISSUE THREAD

**Issue by armsnyder** [armsnyder/countermelody#112]

**Comment by armsnyder** [comment]
Steps to reproduce:
1. Start game.
2. Rest for the first beat, then move player 1's green unit right on beats 2, 3, and 4.
3. Rest for player 2's measure.
4. On the first beat of player 1's second turn, attack player 2's green unit.

**Comment by cegrief** [comment]
can confirm. Any preliminary idea why this is happening?

**Comment by armsnyder** [comment]
I'm actually not able to reproduce this anymore...

... on latest commit to develop

**Comment by cegrief** [comment]
I just got it to happen, but i can't nail down steps to reproduce. It happens fairly consistently when i play for a while so i don't think we can ignore it.
