### ISSUE TITLE
Make BUS

### ISSUE THREAD

**Issue by cegrief** [armsnyder/countermelody#17]
Requires: ASCII BUS art (copy code from slides)

**Comment by armsnyder** [comment]
from slides:

public class GameEvent {
// some fields: event type ID, reference to sender, etc
}
public class GameEventBus : MonoBehaviour {
private Queue<GameEvent> _events;
public event Action<GameEvent> OnGameEvent;
public void AddEvent (... event data) {
GameEvent evt = new GameEvent(...);
_events.Enqueue(evt);
}
public void Update () {
while (_events.Count > 0) {
GameEvent evt = _events.Dequeue();
OnGameEvent(evt);
}
}
}

Does this mean we should do away with the EventHandler delegate altogether and use a custom GameEvent class instead?
