### ISSUE TITLE
Battle Manager script

### ISSUE THREAD

**Issue by cegrief** [armsnyder/countermelody#50]
Does all the things to set up battle screen and kicks off the battle.

**Comment by cegrief** [comment]
Listens on BattleEvent message. This message sends the characters participating in the battle with it.

**Comment by cegrief** [comment]
Handles notes being hit properly, etc. Send a message when battle is over with results and units participating to handle damage accordingly. DealDamage message

**Comment by armsnyder** [comment]
Created stub BattleManager.cs in 9f16977. Contains messages for EnterBattle, ExitBattle, NoteHit, and NoteMiss, which are used by Song.cs to determine when to mute/unmute instrument tracks.
