### ISSUE TITLE
Select Character

### ISSUE THREAD

**Issue by cegrief** [armsnyder/countermelody#8]

**Comment by armsnyder** [comment]
Hi Greg. This is Flame and Fawkes.

We have committed to develop all the code you need to start listening for attack, select, and move messages.

So basically. In your Unit code's Start() method you'll want to subscribe to the UnitActionMessage. You can find examples of how to do this in like all of the code. Look at AttackInterpreter.cs for example.

So then, you need to write a handler method and add a switch statement for the UnitActionMessageType enum that comes as a property of the message (can be ATTACK, MOVE, SELECT) and act accordingly.

ATTACK and SELECT only use PlayerNumber and Color
MOVE uses PlayerNumber and Direction

glhf
